/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.UIManager;
//import javax.swing.JPanel;


/**
 *
 * @author luism
 */

enum EstadoInterfaz{
    SinEstado,Login,Registro,Encriptar,Desencriptar
}

public class Interfaz extends javax.swing.JFrame implements Interfaz_interface{
    
    private int xMouse,yMouse;
    private EstadoInterfaz estado;
    private String pathFichero,nombreLogin,contrasenaLogin,nombreRegistro,contrasena1Registro,contrasena2Registo;
    //private String optionsPathEncriptar,optionsPathDesencriptar;
    
    public PanelIniciarSesion panelIniciarSesion;
    public PanelRegistro panelRegistro;
    public PanelInicio panelInicio;
    public PanelExito panelExito;
   
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        estado = EstadoInterfaz.SinEstado;
        
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
            
        }
        
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(20,39,155)));
        initComponents();
        this.setLocationRelativeTo(null);
        
        panelIniciarSesion = new PanelIniciarSesion(this);
        panelRegistro = new PanelRegistro(this);
        panelInicio = new PanelInicio(this);
        panelExito = new PanelExito(this);
        
        this.ponerPanel(panelIniciarSesion);
        
        this.setVisible(true);
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        tituloHeader = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        Authors = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        tituloMain = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Header.setBackground(new java.awt.Color(92, 122, 234));
        Header.setPreferredSize(new java.awt.Dimension(800, 35));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        BotonCerrar.setBackground(new java.awt.Color(92, 122, 234));
        BotonCerrar.setPreferredSize(new java.awt.Dimension(40, 40));

        cerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonCerrarLayout = new javax.swing.GroupLayout(BotonCerrar);
        BotonCerrar.setLayout(BotonCerrarLayout);
        BotonCerrarLayout.setHorizontalGroup(
            BotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonCerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonCerrarLayout.setVerticalGroup(
            BotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        Header.add(BotonCerrar, java.awt.BorderLayout.LINE_END);

        tituloHeader.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tituloHeader.setText("   CS Encrypter");
        Header.add(tituloHeader, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Footer.setPreferredSize(new java.awt.Dimension(800, 30));

        Authors.setBackground(new java.awt.Color(92, 122, 234));
        Authors.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Authors.setForeground(new java.awt.Color(92, 122, 234));
        Authors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Authors.setText(" Britt Hooghiemstra, Luis Morata, Santos Muñoz, Lucía Oliva");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authors, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authors, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        Main.setBackground(new java.awt.Color(230, 230, 230));
        Main.setLayout(new java.awt.BorderLayout());

        tituloPanel.setPreferredSize(new java.awt.Dimension(800, 80));

        tituloMain.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tituloMain.setForeground(new java.awt.Color(92, 122, 234));
        tituloMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMain.setText("CS Encrypter");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloMain, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloPanelLayout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(tituloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Main.add(tituloPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        Main.add(content, java.awt.BorderLayout.CENTER);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        BotonCerrar.setBackground(new Color(61,39,155));
        cerrar.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        BotonCerrar.setBackground(new Color(92,122,234));
        cerrar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_cerrarMouseExited

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse= evt.getX();
        yMouse =evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged
    
    
        
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Authors;
    private javax.swing.JPanel BotonCerrar;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPanel content;
    private javax.swing.JLabel tituloHeader;
    private javax.swing.JLabel tituloMain;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables

    public void ponerPanel(JPanel p){
        p.setSize(800, 355);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    public void Login(String _nombre, String _pass){
        nombreLogin = _nombre;
        contrasenaLogin = _pass;
        cambiarEstado(EstadoInterfaz.Login);
    }
    
    public void ErrorLogin(){
        cambiarEstado(EstadoInterfaz.SinEstado);
        panelIniciarSesion.Error();
    }
    
    public void ExitoLogin(){
        cambiarEstado(EstadoInterfaz.SinEstado);
        panelExito.Exito("Has iniciado sesión correctamente");
        ponerPanel(panelExito);
    }
    
    public void Registro(String _nombre, String _pass){
        nombreRegistro = _nombre;
        contrasena1Registro = _pass;
        cambiarEstado(EstadoInterfaz.Registro);    
    }
    
    public void ErrorRegistro(String _error){
        cambiarEstado(EstadoInterfaz.SinEstado);
        panelRegistro.Error(_error);
    }
    
    public void ExitoRegistro(){
        cambiarEstado(EstadoInterfaz.SinEstado);
        panelExito.Exito("Te has registrado correctamente");
        ponerPanel(panelExito);
        
    }
    
    public void Encriptar(String _path){
        pathFichero = _path;
        cambiarEstado(EstadoInterfaz.Encriptar);
    }
    
    public void Desencriptar(String _path){
        pathFichero = _path;
        cambiarEstado(EstadoInterfaz.Desencriptar);
    }
    
    @Override
    public EstadoInterfaz dameEstado() {
        return estado;
    }

    public void cambiarEstado(EstadoInterfaz _estado){
        estado = _estado;
        //System.out.println("DEBERIA ENTRAR AQUI");
    }
    
    @Override
    public String damePathFichero() {
        return pathFichero;
    }

    @Override
    public String dameNombreLogin() {
        return nombreLogin;
    }

    @Override
    public String dameContrasenaLogin() {
        return contrasenaLogin;
    }

    @Override
    public String dameNombreRegistro() {
        return nombreRegistro;
    }

    @Override
    public String dameContrasena1Registro() {
        return contrasena1Registro;
    }

    @Override
    public String dameContrasena2Registro() {
        return contrasena2Registo;
    }

    
}
