/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
//import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author luism
 */
public class Interfaz extends javax.swing.JFrame {
    
    private final JFileChooser openEncriptar, openDesencriptar;
    private int xMouse,yMouse;
    
    public String pathEncriptar, pathDesencriptar;
    
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(20,39,155)));
        initComponents();
        desencriptarResult.setText("");
        encriptarResult.setText("");
        this.setLocationRelativeTo(null);
        
        pathDesencriptar ="";
        pathEncriptar = "";
        

        openEncriptar = new JFileChooser();
        openEncriptar.setCurrentDirectory(new File("decript"));
        openDesencriptar = new JFileChooser();
        openDesencriptar.setCurrentDirectory(new File("encript"));
        openDesencriptar.setFileFilter(new FileNameExtensionFilter("Encryted files","enc"));
    }
    
    /*
    public void TerminarEncriptar(){
        pathEncriptar = "";
        estado = EstadoInterfaz.SINPATH;
    }
    
    public void TerminarDesencriptar(){
        pathDesencriptar = "";
        estado = EstadoInterfaz.SINPATH;
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        BotonCerrar = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        tituloHeader = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        Authors = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        tituloMain = new javax.swing.JLabel();
        BotonesMain = new javax.swing.JPanel();
        Encriptar = new javax.swing.JPanel();
        EncriptarTxt = new javax.swing.JLabel();
        Desencriptar = new javax.swing.JPanel();
        DesencriptarTxt = new javax.swing.JLabel();
        encriptarResult = new javax.swing.JLabel();
        desencriptarResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Header.setBackground(new java.awt.Color(92, 122, 234));
        Header.setPreferredSize(new java.awt.Dimension(800, 40));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new java.awt.BorderLayout());

        BotonCerrar.setBackground(new java.awt.Color(92, 122, 234));
        BotonCerrar.setPreferredSize(new java.awt.Dimension(40, 40));

        cerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setText("X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BotonCerrarLayout = new javax.swing.GroupLayout(BotonCerrar);
        BotonCerrar.setLayout(BotonCerrarLayout);
        BotonCerrarLayout.setHorizontalGroup(
            BotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonCerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonCerrarLayout.setVerticalGroup(
            BotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Header.add(BotonCerrar, java.awt.BorderLayout.LINE_END);

        tituloHeader.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tituloHeader.setText("   CS Encrypter");
        Header.add(tituloHeader, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Footer.setBackground(new java.awt.Color(230, 230, 230));
        Footer.setPreferredSize(new java.awt.Dimension(800, 30));

        Authors.setBackground(new java.awt.Color(92, 122, 234));
        Authors.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Authors.setForeground(new java.awt.Color(92, 122, 234));
        Authors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Authors.setText(" Britt Hooghiemstra, Luis Morata, Santos Muñoz, Lucía Oliva");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authors, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Authors, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        Main.setBackground(new java.awt.Color(230, 230, 230));
        Main.setLayout(new java.awt.BorderLayout());

        tituloPanel.setBackground(new java.awt.Color(230, 230, 230));

        tituloMain.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tituloMain.setForeground(new java.awt.Color(92, 122, 234));
        tituloMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMain.setText("CS Encrypter");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloMain, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tituloMain, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Main.add(tituloPanel, java.awt.BorderLayout.PAGE_START);

        BotonesMain.setBackground(new java.awt.Color(230, 230, 230));

        Encriptar.setBackground(new java.awt.Color(92, 122, 234));

        EncriptarTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EncriptarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EncriptarTxt.setText("Encriptar");
        EncriptarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncriptarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EncriptarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EncriptarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EncriptarLayout = new javax.swing.GroupLayout(Encriptar);
        Encriptar.setLayout(EncriptarLayout);
        EncriptarLayout.setHorizontalGroup(
            EncriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncriptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EncriptarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EncriptarLayout.setVerticalGroup(
            EncriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EncriptarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Desencriptar.setBackground(new java.awt.Color(92, 122, 234));

        DesencriptarTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DesencriptarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesencriptarTxt.setText("Desencriptar");
        DesencriptarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesencriptarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DesencriptarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DesencriptarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DesencriptarLayout = new javax.swing.GroupLayout(Desencriptar);
        Desencriptar.setLayout(DesencriptarLayout);
        DesencriptarLayout.setHorizontalGroup(
            DesencriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesencriptarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesencriptarLayout.setVerticalGroup(
            DesencriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesencriptarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        encriptarResult.setBackground(new java.awt.Color(92, 122, 234));
        encriptarResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        encriptarResult.setForeground(new java.awt.Color(92, 122, 234));
        encriptarResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encriptarResult.setText(" Britt Hooghiemstra, Luis Morata, Santos Muñoz, Lucía Oliva");

        desencriptarResult.setBackground(new java.awt.Color(92, 122, 234));
        desencriptarResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        desencriptarResult.setForeground(new java.awt.Color(92, 122, 234));
        desencriptarResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desencriptarResult.setText(" Britt Hooghiemstra, Luis Morata, Santos Muñoz, Lucía Oliva");

        javax.swing.GroupLayout BotonesMainLayout = new javax.swing.GroupLayout(BotonesMain);
        BotonesMain.setLayout(BotonesMainLayout);
        BotonesMainLayout.setHorizontalGroup(
            BotonesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BotonesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Encriptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Desencriptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(274, 274, 274))
            .addGroup(BotonesMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotonesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encriptarResult, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(desencriptarResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        BotonesMainLayout.setVerticalGroup(
            BotonesMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesMainLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Encriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(encriptarResult, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Desencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desencriptarResult, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(126, 126, 126))
        );

        Main.add(BotonesMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        BotonCerrar.setBackground(new Color(61,39,155));
        cerrar.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        BotonCerrar.setBackground(new Color(92,122,234));
        cerrar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_cerrarMouseExited

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse= evt.getX();
        yMouse =evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void EncriptarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncriptarTxtMouseEntered
        Encriptar.setBackground(new Color(61,39,155));
        EncriptarTxt.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_EncriptarTxtMouseEntered

    private void EncriptarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncriptarTxtMouseExited
        Encriptar.setBackground(new Color(92,122,234));
        EncriptarTxt.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_EncriptarTxtMouseExited

    private void EncriptarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncriptarTxtMouseClicked
        int returnValue = openEncriptar.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            pathEncriptar = openEncriptar.getSelectedFile().getPath();
            encriptarResult.setText(openEncriptar.getSelectedFile().getName());
        } else{
            encriptarResult.setText("No se ha seleccionado ningun archivo");
        }
    }//GEN-LAST:event_EncriptarTxtMouseClicked

    private void DesencriptarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarTxtMouseEntered
        Desencriptar.setBackground(new Color(61,39,155));
        DesencriptarTxt.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_DesencriptarTxtMouseEntered

    private void DesencriptarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarTxtMouseExited
        Desencriptar.setBackground(new Color(92,122,234));
        DesencriptarTxt.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_DesencriptarTxtMouseExited

    private void DesencriptarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarTxtMouseClicked
        int returnValue = openDesencriptar.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            pathDesencriptar = openDesencriptar.getSelectedFile().getPath();
            desencriptarResult.setText(openDesencriptar.getSelectedFile().getName());
        } else{
            desencriptarResult.setText("No se ha seleccionado ningun archivo");
        }
    }//GEN-LAST:event_DesencriptarTxtMouseClicked
    
    
        
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Authors;
    private javax.swing.JPanel BotonCerrar;
    private javax.swing.JPanel BotonesMain;
    private javax.swing.JPanel Desencriptar;
    private javax.swing.JLabel DesencriptarTxt;
    private javax.swing.JPanel Encriptar;
    private javax.swing.JLabel EncriptarTxt;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel desencriptarResult;
    private javax.swing.JLabel encriptarResult;
    private javax.swing.JLabel tituloHeader;
    private javax.swing.JLabel tituloMain;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
