/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author luism
 */
public class PanelObtenerFicheros extends javax.swing.JPanel {

    /**
     * Creates new form panelPlantilla
     */
    Interfaz interfaz;
    public PanelObtenerFicheros(Interfaz i) {
        interfaz = i;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDerecho = new javax.swing.JPanel();
        PanelIzquierdo = new javax.swing.JPanel();
        PanelCentral = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JLabel();
        DesencriptarBoton = new javax.swing.JPanel();
        DesencriptarBotonTxt = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        listaArchivos = new javax.swing.JList<>();
        VolverBoton = new javax.swing.JPanel();
        VolverBotonTxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 355));
        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanelDerechoLayout = new javax.swing.GroupLayout(PanelDerecho);
        PanelDerecho.setLayout(PanelDerechoLayout);
        PanelDerechoLayout.setHorizontalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelDerechoLayout.setVerticalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        add(PanelDerecho, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout PanelIzquierdoLayout = new javax.swing.GroupLayout(PanelIzquierdo);
        PanelIzquierdo.setLayout(PanelIzquierdoLayout);
        PanelIzquierdoLayout.setHorizontalGroup(
            PanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelIzquierdoLayout.setVerticalGroup(
            PanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        add(PanelIzquierdo, java.awt.BorderLayout.LINE_END);

        tituloPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloPanel.setForeground(new java.awt.Color(92, 122, 234));
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Seleccione un archivo para desencriptar");

        DesencriptarBoton.setBackground(new java.awt.Color(92, 122, 234));

        DesencriptarBotonTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DesencriptarBotonTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesencriptarBotonTxt.setText("Desencriptar");
        DesencriptarBotonTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesencriptarBotonTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DesencriptarBotonTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DesencriptarBotonTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DesencriptarBotonLayout = new javax.swing.GroupLayout(DesencriptarBoton);
        DesencriptarBoton.setLayout(DesencriptarBotonLayout);
        DesencriptarBotonLayout.setHorizontalGroup(
            DesencriptarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesencriptarBotonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DesencriptarBotonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        DesencriptarBotonLayout.setVerticalGroup(
            DesencriptarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesencriptarBotonTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        listaArchivos.setBackground(new java.awt.Color(139, 163, 255));
        listaArchivos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaArchivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "example.png (usuario)", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaArchivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaArchivos.setSelectionBackground(new java.awt.Color(74, 108, 218));
        scrollPanel.setViewportView(listaArchivos);

        VolverBoton.setBackground(new java.awt.Color(92, 122, 234));

        VolverBotonTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VolverBotonTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VolverBotonTxt.setText("Volver");
        VolverBotonTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverBotonTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverBotonTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverBotonTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout VolverBotonLayout = new javax.swing.GroupLayout(VolverBoton);
        VolverBoton.setLayout(VolverBotonLayout);
        VolverBotonLayout.setHorizontalGroup(
            VolverBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolverBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VolverBotonTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        VolverBotonLayout.setVerticalGroup(
            VolverBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VolverBotonTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelCentralLayout = new javax.swing.GroupLayout(PanelCentral);
        PanelCentral.setLayout(PanelCentralLayout);
        PanelCentralLayout.setHorizontalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCentralLayout.createSequentialGroup()
                        .addComponent(VolverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DesencriptarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelCentralLayout.setVerticalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesencriptarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        add(PanelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void DesencriptarBotonTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarBotonTxtMouseClicked
        DesencriptarBoton.setBackground(new Color(92,122,234));
        DesencriptarBotonTxt.setForeground(new Color(0,0,0));
        interfaz.SolicitarFichero(listaArchivos.getSelectedValue());
    }//GEN-LAST:event_DesencriptarBotonTxtMouseClicked

    private void DesencriptarBotonTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarBotonTxtMouseEntered
        DesencriptarBoton.setBackground(new Color(61,39,155));
        DesencriptarBotonTxt.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_DesencriptarBotonTxtMouseEntered

    private void DesencriptarBotonTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarBotonTxtMouseExited
        DesencriptarBoton.setBackground(new Color(92,122,234));
        DesencriptarBotonTxt.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_DesencriptarBotonTxtMouseExited

    private void VolverBotonTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBotonTxtMouseClicked
        VolverBoton.setBackground(new Color(92,122,234));
        VolverBotonTxt.setForeground(new Color(0,0,0));
        interfaz.ponerPanel(interfaz.panelInicio);
    }//GEN-LAST:event_VolverBotonTxtMouseClicked

    private void VolverBotonTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBotonTxtMouseEntered
        VolverBoton.setBackground(new Color(61,39,155));
        VolverBotonTxt.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_VolverBotonTxtMouseEntered

    private void VolverBotonTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBotonTxtMouseExited
        VolverBoton.setBackground(new Color(92,122,234));
        VolverBotonTxt.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_VolverBotonTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DesencriptarBoton;
    private javax.swing.JPanel DesencriptarBoton1;
    private javax.swing.JLabel DesencriptarBotonTxt;
    private javax.swing.JLabel DesencriptarBotonTxt1;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelDerecho;
    private javax.swing.JPanel PanelIzquierdo;
    private javax.swing.JPanel VolverBoton;
    private javax.swing.JLabel VolverBotonTxt;
    private javax.swing.JList<String> listaArchivos;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JLabel tituloPanel;
    // End of variables declaration//GEN-END:variables

    public void PonerValores(ArrayList<String> _datos){
        listaArchivos.setModel(new DefaultListModel());
        DefaultListModel modelo = (DefaultListModel) listaArchivos.getModel();
        for(int i=0;i<_datos.size();i++){
            modelo.addElement(_datos.get(i));  
        }
    }

}
