/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author luism
 */
public class PanelOpciones extends javax.swing.JPanel {

    /**
     * Creates new form panelPlantilla
     */
    private final JFileChooser openEncriptar, openDesencriptar;
    Interfaz interfaz;
    public PanelOpciones(Interfaz i) {
        interfaz = i;
        initComponents();
        
        openEncriptar = new JFileChooser();
        openEncriptar.setCurrentDirectory(new File("data\\desencriptado"));
        openDesencriptar = new JFileChooser();
        openDesencriptar.setCurrentDirectory(new File("data\\encriptado"));
        openDesencriptar.setFileFilter(new FileNameExtensionFilter("Encryted files","enc"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDerecho = new javax.swing.JPanel();
        PanelIzquierdo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelCentral = new javax.swing.JPanel();
        Encriptar = new javax.swing.JPanel();
        EncriptarTxt = new javax.swing.JLabel();
        Desencriptar = new javax.swing.JPanel();
        DesencriptarTxt = new javax.swing.JLabel();
        encriptarResult = new javax.swing.JLabel();
        desencriptarResult = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 355));
        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanelDerechoLayout = new javax.swing.GroupLayout(PanelDerecho);
        PanelDerecho.setLayout(PanelDerechoLayout);
        PanelDerechoLayout.setHorizontalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelDerechoLayout.setVerticalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        add(PanelDerecho, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout PanelIzquierdoLayout = new javax.swing.GroupLayout(PanelIzquierdo);
        PanelIzquierdo.setLayout(PanelIzquierdoLayout);
        PanelIzquierdoLayout.setHorizontalGroup(
            PanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelIzquierdoLayout.setVerticalGroup(
            PanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        add(PanelIzquierdo, java.awt.BorderLayout.LINE_END);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        Encriptar.setBackground(new java.awt.Color(92, 122, 234));

        EncriptarTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EncriptarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EncriptarTxt.setText("Encriptar");
        EncriptarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncriptarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EncriptarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EncriptarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EncriptarLayout = new javax.swing.GroupLayout(Encriptar);
        Encriptar.setLayout(EncriptarLayout);
        EncriptarLayout.setHorizontalGroup(
            EncriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncriptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EncriptarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EncriptarLayout.setVerticalGroup(
            EncriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncriptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EncriptarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Desencriptar.setBackground(new java.awt.Color(92, 122, 234));

        DesencriptarTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DesencriptarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesencriptarTxt.setText("Desencriptar");
        DesencriptarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesencriptarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DesencriptarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DesencriptarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DesencriptarLayout = new javax.swing.GroupLayout(Desencriptar);
        Desencriptar.setLayout(DesencriptarLayout);
        DesencriptarLayout.setHorizontalGroup(
            DesencriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesencriptarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(DesencriptarTxt)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        DesencriptarLayout.setVerticalGroup(
            DesencriptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesencriptarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DesencriptarTxt)
                .addContainerGap())
        );

        encriptarResult.setBackground(new java.awt.Color(92, 122, 234));
        encriptarResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        encriptarResult.setForeground(new java.awt.Color(92, 122, 234));
        encriptarResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encriptarResult.setText("b");

        desencriptarResult.setBackground(new java.awt.Color(92, 122, 234));
        desencriptarResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        desencriptarResult.setForeground(new java.awt.Color(92, 122, 234));
        desencriptarResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desencriptarResult.setText("b");

        javax.swing.GroupLayout PanelCentralLayout = new javax.swing.GroupLayout(PanelCentral);
        PanelCentral.setLayout(PanelCentralLayout);
        PanelCentralLayout.setHorizontalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Encriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(encriptarResult, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Desencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(desencriptarResult, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelCentralLayout.setVerticalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCentralLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Encriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(encriptarResult)
                .addGap(25, 25, 25)
                .addComponent(Desencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(desencriptarResult))
        );

        add(PanelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void EncriptarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncriptarTxtMouseClicked
        int returnValue = openEncriptar.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            interfaz.Encriptar(openEncriptar.getSelectedFile().getPath());
            encriptarResult.setText(openEncriptar.getSelectedFile().getName());
        } else{
            encriptarResult.setText("No se ha seleccionado ningun archivo");
        }
    }//GEN-LAST:event_EncriptarTxtMouseClicked

    private void EncriptarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncriptarTxtMouseEntered
        Encriptar.setBackground(new Color(61,39,155));
        EncriptarTxt.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_EncriptarTxtMouseEntered

    private void EncriptarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncriptarTxtMouseExited
        Encriptar.setBackground(new Color(92,122,234));
        EncriptarTxt.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_EncriptarTxtMouseExited

    private void DesencriptarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarTxtMouseClicked
        int returnValue = openDesencriptar.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            interfaz.Desencriptar(openDesencriptar.getSelectedFile().getPath());
            desencriptarResult.setText(openDesencriptar.getSelectedFile().getName());
        } else{
            desencriptarResult.setText("No se ha seleccionado ningun archivo");
        }
    }//GEN-LAST:event_DesencriptarTxtMouseClicked

    private void DesencriptarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarTxtMouseEntered
        Desencriptar.setBackground(new Color(61,39,155));
        DesencriptarTxt.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_DesencriptarTxtMouseEntered

    private void DesencriptarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesencriptarTxtMouseExited
        Desencriptar.setBackground(new Color(92,122,234));
        DesencriptarTxt.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_DesencriptarTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desencriptar;
    private javax.swing.JLabel DesencriptarTxt;
    private javax.swing.JPanel Encriptar;
    private javax.swing.JLabel EncriptarTxt;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelDerecho;
    private javax.swing.JPanel PanelIzquierdo;
    private javax.swing.JLabel desencriptarResult;
    private javax.swing.JLabel encriptarResult;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
